export { urqlClient } from '@/api/client'
export { GET_POSTS } from '@/api/queries/posts'
export type { GetPostsQuery, GetPostsVariables } from '@/api/queries/posts'
export { LOGIN, LOGOUT } from '@/api/mutations/auth'
export type { LoginMutation, LoginVariables, LogoutMutation } from '@/api/mutations/auth'
export type { Post, PostConnection, LoginInput, LoginPayload } from '@/api/types/common'
